org: jsoareez
service: jwt

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  architecture: arm64
  memorySize: 128
  timeout: 25
  environment:
    DYNAMO_APPLICATION_TABLE: !Ref ApplicationTable
    DYNAMO_STORAGE_TABLE: !Ref StorageTable
    UPLOAD_BUCKET: !Ref UploadBucket
  iam:
    role:
      statements:
        # DynamoDB
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource:
            - !GetAtt ApplicationTable.Arn
            - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ApplicationTable}/index/GSI1
            - !GetAtt StorageTable.Arn
        # S3
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: !Join ['/', [!GetAtt UploadBucket.Arn, '*']]

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

custom:
  serverless-offline:
    httpPort: 4000
    localEnvironment: true

functions:
  # Account
  AccountSignIn:
    handler: src/app/modules/Account/handler.signInHandler
    events:
      - httpApi:
          path: /account/sign-in
          method: POST
  AccountSignUp:
    handler: src/app/modules/Account/handler.signUpHandler
    events:
      - httpApi:
          path: /account/sign-up
          method: POST

  # Storage
  GetPresignedUrl:
    handler: src/app/modules/Storage/handler.getPresignedUrlHandler
    events:
      - httpApi:
          path: /storage/get-presigned-url
          method: POST

  # Private Routes
  ListLeads:
    handler: src/app/modules/Leads/handler.listLeadsHandler
    events:
      - httpApi:
          path: /leads
          method: GET
  PrivateLeads:
    handler: src/app/modules/Leads/handler.privateLeadsHandler
    events:
      - httpApi:
          path: /leads
          method: POST

resources:
  # DynamoDB
  - ${file(./resources/dynamodb/ApplicationTable.yml)}
  - ${file(./resources/dynamodb/StorageTable.yml)}
  # S3 Bucket
  - ${file(./resources/s3/UploadBucket.yml)}
